name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensures deployment happens only after the tests pass

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger deployment on Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # GitHub Secret for Render API Key
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"serviceId": "srv-cumel852ng1s7382b690"}' \
            https://api.render.com/v1/services/trigger/deploy
